[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash scripts/railway_start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "core.settings_prod"

# Explicitly request a MySQL database
[[services]]
name = "mysql"
image = "mysql:8.0"
environment = { MYSQL_ROOT_PASSWORD = "${DB_PASSWORD}", MYSQL_DATABASE = "${DB_NAME:-community}" }

# Link the MySQL service to the web service
[[services.links]]
service = "web"
environment = { MYSQL_HOST = "mysql", MYSQL_PORT = "3306", MYSQL_USER = "root", MYSQL_PASSWORD = "${DB_PASSWORD}", MYSQL_DATABASE = "${DB_NAME:-community}" }
